# Generated by Django 4.2.5 on 2023-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(max_length=20),
        ),
    ]
