# Generated by Django 4.2.5 on 2023-10-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_computer_export_to_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='export_to_CSV',
        ),
    ]
