# Generated by Django 4.2.5 on 2023-10-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_computer_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
